system:
    device: cuda

data:
    images_path: src/data/UIT-ViIC/dataset/train/images
    annotations_path: src/data/UIT-ViIC/dataset/train/train.json
    context_length: 77
    shuffle_captions: True
    batch_size: 64

model:
    from_pretrained: True
    proj_dim: 256

algorithm:
    loss: siglip # clip/siglip
    epochs: 5
    learning_rate: 1e-4
    weight_decay: 0.0